name: Go

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    services: 
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: casbin
        ports:
          - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/checkout@v4
      - name: Run Unit tests
        run: go test -v -coverprofile=profile.cov ./...
      
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github

  semantic-release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Run semantic-release
        if: github.repository == 'casbin/xorm-adapter' && github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}